//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public System.Guid TaskId { get; set; }
        public System.Guid AuthorId { get; set; }
        public byte[] File1 { get; set; }
        public string Name { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
